In [ ]:
import numpy as np

In [15]:
working_array = np.arange(25).reshape(5, 5)

print(working_array)

# boolean indexing is a built in feature of ndarrays that allow us to interact with subsets of the array data based
# upon a specified condition
subset_1 = working_array[working_array <=7]

print(subset_1)

# we can get pretty sophisticated with these conditionals (it appears to be just as you would with a if-else statement)
subset_2 = working_array[(working_array > 3) & (working_array < 10)]

print(subset_2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[0 1 2 3 4 5 6 7]
[4 5 6 7 8 9]


In [ ]:
working_array_1 = np.array([1, 2, 3, 4, 5])
working_array_2 = np.array([1, 6, 7, 8, 9])

# we can also use numpy to perform comparisons between two collections
subset_1 = np.intersect1d(working_array_1, working_array_2)
subset_2 = np.setdiff1d(working_array_1, working_array_2)
subset_3 = np.union1d(working_array_1, working_array_2)

print(subset_1)
print(subset_2)
print(subset_3)

In [ ]:
working_array = np.random.randint(1, 11, size=(10,))

# sorting working array using np.sort ("function") sorts the argument out of place - not modifying the original array.
# if you look at the output, below, the original remains different from the result.
subset_1 = np.sort(working_array)

print(working_array)
print(subset_1)

# when sorted on the object, itself, as a method, notice the difference (not only is the array sorted in place, but a new
# array instance is not returned, hence "None"
subset_2 = working_array.sort()

print(working_array)
print(subset_2)

# by supplying an axis=0/1 argument, we can also sort 2D arrays