In [ ]:
import numpy as np

a = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])

print(a)

a[1, 0] = 0

print(a)

In [ ]:
b = np.linspace(0, 20, 10, endpoint=True, retstep=False, dtype="int64")

print(b)

# delete elements from a flat array
b = np.delete(b, [0])

print(b)

# more complex delete interactions with two-dimensional arrays
# using .full for ease
c = np.full((4, 4), 1)

print(c)

# this performs the removal of a speified (0; index) row (axis=0 === rows)
c = np.delete(c, 0, axis=0)

print(c)

# this performs the removal of a speified (1; index) column (axis=1 === columns)
c = np.delete(c, [1], axis=1)

print(c)

In [33]:
d = np.full((4, 4), 1)

print(d)

# append a new row containig fives along the row (0) axis
d = np.append(d, [[5, 5, 5, 5]], axis=0)

print(d)

# append a new column containing sixes along the column (1) axis
d = np.append(d, [[6], [6], [6], [6], [6]], axis=1)

print(d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]]
[[1 1 1 1 6]
 [1 1 1 1 6]
 [1 1 1 1 6]
 [1 1 1 1 6]
 [5 5 5 5 6]]
